markdown: kramdown
author: paitiewfrance

permalink: pretty

url: "http://paitiewfrance.com"



navigation:
  - label: home
    title: home
    url: /
  - label: Tour Provence 
    title: Tour Provence
    url: /tour-provence
    sub-menu:
       - label: Wonder of Eastern Provence
         title: Wonder of Eastern Provence
         url: /tour-provence/wonder-eastern-provence
       - label: Wonder and Lavender Provence
         title: Wonder and Lavender Provence
         url: /tour-provence/wonder-and-lavender-provence
       - label: The French Riviera by the Seaside
         title: The French Riviera by the Seaside
         url: /tour-provence/the-french-riviera-by-the-seaside
  - label: Tour Burgundy
    title: Tour Burgundy
    url: /tour-burgundy
    sub-menu:
       - label: Wonderfull Burgundy 
         title:  Wonderfull Burgundy 
         url: /tour-burgundy/wonderfull-burgundy
       - label: Burgundy Eight days
         title:  Burgundy Eight days
         url: /tour-burgundy/burgundy-eight-days
  - label: Tour Alps
    title: Tour Alps
    url: /tour-alps
    sub-menu:
       - label: Road of the great Alps
         title: Road of the great Alps
         url: /tour-alps/road-of-great-alps
  - label: Tour Aveyron Tarn
    title: Aveyron Tarn
    url: /tour-aveyron-tarn
  - label: about us
    title: about us
    url: /about
  - label: contact
    title: contact
    url: /contact
  - label: blog
    title: blog
    url: /blog


