markdown: kramdown
author: paitiewfrance

permalink: pretty

url: "http://paitiewfrance.com"



navigation:
  - label: ไปเที่ยวฟรานซ์
    title: ไปเที่ยวฟรานซ์
    url: /
  - label: ทัวร์โพรวองซ์ 
    title:  ทัวร์โพรวองซ์
    url: /tour-provence
    sub-menu:
       - label: วันเดอร์ โพรวองซ์ ตะวันออก
         title: วันเดอร์ โพรวองซ์ ตะวันออก
         url: /tour-provence/wonder-eastern-provence
       - label: วันเดอร์ ลาเวนเดอร์ โพรวองซ์
         title: วันเดอร์ ลาเวนเดอร์ โพรวองซ์
         url: /tour-provence/wonder-and-lavender-provence
       - label: ชายฝั่งเฟรนช์ ริเวียร่า
         title: ชายฝั่งเฟรนช์ ริเวียร่า
         url: /tour-provence/the-french-riviera-by-the-seaside
  - label:  ทัวร์แคว้นเบอร์กันดี
    title:  ทัวร์แคว้นเบอร์กันดี
    url: /tour-burgundy
    sub-menu:
       - label: วันเดอร์เบอร์กันดีตอนเหนือ
         title:  วันเดอร์เบอร์กันดีตอนเหนือ
         url: /tour-burgundy/wonder-northern-burgundy
       - label: เส้นทางไวน์แห่งเบอร์กันดีและเบอร์กันดีตอนใต้
         title:  เส้นทางไวน์แห่งเบอร์กันดีและเบอร์กันดีตอนใต้
         url: /tour-burgundy/road-of-wine-and-southern-burgundy
       - label: แกรนด์เบอร์กันดี 
         title: แกรนด์เบอร์กันดี
         url: /tour-burgundy/grand-burgundy
  - label:  ทัวร์เทือกเขาแอลป์
    title:  ทัวร์เทือกเขาแอลป์
    url: /tour-alps
    sub-menu:
       - label: เส้นทางเทือกเขาแอลป์
         title: เส้นทางเทือกเขาแอลป์
         url: /tour-alps/road-of-great-alps
  - label:  ทัวร์แคว้นมีดี-ปีเรเน (Midi-Pyrénées)
    title: ทัวร์แคว้นมีดี-ปีเรเน (Midi-Pyrénées)
    url: /tour-aveyron-tarn
  - label: เกี่ยวกับไปเที่ยวฟรานซ์
    title: เกี่ยวกับไปเที่ยวฟรานซ์
    url: /about
  - label: ติดต่อไปเที่ยวฟรานซ์
    title: ติดต่อไปเที่ยวฟรานซ์
    url: /contact
  - label:  บล็อกเที่ยวฝรั่งเศส
    title: บล็อกเที่ยวฝรั่งเศส
    url: /blog


