markdown: kramdown
author: paitiewfrance

permalink: pretty

url: "http://paitiewfrance.com"
url: "http://localhost:4000"



navigation:
  - label: ไปเที่ยวฟรานซ์
    title: ไปเที่ยวฟรานซ์
    url: /
  - label: ทัวร์โพรวองซ์ 
    title:  ทัวร์โพรวองซ์
    url: /tour-provence
    sub-menu:
       - label: วันเดอร์ โพรวองซ์ ตะวันออก
         title: วันเดอร์ โพรวองซ์ ตะวันออก
         url: /tour-provence/wonder-eastern-provence
       - label: วันเดอร์ ลาเวนเดอร์ โพรวองซ์
         title: วันเดอร์ ลาเวนเดอร์ โพรวองซ์
         url: /tour-provence/wonder-and-lavender-provence
       - label: ชายฝั่งเฟรนช์ ริเวียร่า
         title: ชายฝั่งเฟรนช์ ริเวียร่า
         url: /tour-provence/the-french-riviera-by-the-seaside
  - label:  ทัวร์แคว้นเบอร์กันดี
    title:  ทัวร์แคว้นเบอร์กันดี
    url: /tour-burgundy
    sub-menu:
       - label: วันเดอร์เบอร์กันดีตอนเหนือ
         title:  วันเดอร์เบอร์กันดีตอนเหนือ
         url: /tour-burgundy/wonder-northern-burgundy
       - label: แกรนด์เบอร์กันดี 
         title: แกรนด์เบอร์กันดี
         url: /tour-burgundy/grand-burgundy
  - label:  ทัวร์เทือกเขาแอลป์
    title:  ทัวร์เทือกเขาแอลป์
    url: /tour-alps
    sub-menu:
       - label: เส้นทางเทือกเขาแอลป์
         title: เส้นทางเทือกเขาแอลป์
         url: /tour-alps/road-of-great-alps
  - label:  ลองด็อค-รูซิยง-มิดิเพเรเน่ (Midi-Pyrénées)
    title: ลองด็อค-รูซิยง-มิดิเพเรเน่ (Midi-Pyrénées)
    url: /tour-languedoc-roussillon-midi-pyrenee
    sub-menu: 
       - label: กรองด์ไซต์พีเรเน่
         title: กรองด์ไซต์พีเรเน่
         url: /tour-languedoc-roussillon-midi-pyrenee/grand-site-pyrenees
       - label: ตูลูส-คาร์คาซอน-กาตาร์-ออช
         title: ตูลูส-คาร์คาซอน-กาตาร์-ออช
         url: /tour-languedoc-roussillon-midi-pyrenee/toulouse-carcassonne-cathare-albi-auch
       # - label: ขุมทรัพย์ที่ซ่อนอยู่ในแคว้นมิดิ-พีเรเน่
       #   title: ขุมทรัพย์ที่ซ่อนอยู่ในแคว้นมิดิ-พีเรเน่
       #   url: /tour-languedoc-roussillon-midi-pyrenee/hidden-treasure-of-pyrenee
  - label:  ทัวร์ แคว้นอาลซัส Alsace
    title:  ทัวร์ แคว้นอาลซัส Alsace
    url: /tour-alsace
    sub-menu: 
       - label:  ทัวร์คริสต์มาสแคว้นอาลซัส
         title:  ทัวร์คริสต์มาสแคว้นอาลซัส
         url: /tour-alsace/christmas-in-alsace
       # - label: เส้นทางแห่งไวน์
       #   title: เส้นทางแห่งไวน์
       #   url: /tour-alsace/road-of-wine
  - label: ทัวร์ เปยี เดอ ลา ลัวร์
    title: ทัวร์ เปยี เดอ ลา ลัวร์
    url: /tour-pays-de-la-loire
    sub-menu:
       - label: ปราสาทแห่งลุ่มแม่น้ำลัวร์
         title: ปราสาทแห่งลุ่มแม่น้ำลัวร์
         url: /tour-pays-de-la-loire/castles-of-the-loire-valley
  - label: เกี่ยวกับไปเที่ยวฟรานซ์
    title: เกี่ยวกับไปเที่ยวฟรานซ์
    url: /about
  - label: ติดต่อไปเที่ยวฟรานซ์
    title: ติดต่อไปเที่ยวฟรานซ์
    url: /contact
  - label:  บล็อกเที่ยวฝรั่งเศส
    title: บล็อกเที่ยวฝรั่งเศส
    url: /blog


