markdown: kramdown
author: paitiewfrance

permalink: pretty

url: "http://paitiewfrance.com"



navigation:
  - label: home
    title: home
    url: /
  - label: Wonder of Eastern Provence
    title: Wonder of Eastern Provence
    url: /wonder-eastern-provence
  - label: The French Riviera by the Seaside
    title: The French Riviera by the Seaside
    url: /the-french-riviera-by-the-seaside
  - label: Road of the great Alps
    title: Road of the great Alps
    url: /road-of-great-alps
  - label: Wonder and Lavender in Provence
    title: Wonder and Lavender in Provence
    url: /wonder-and-lavender-provence
  - label: Wonderfull Burgundy 
    title:  Wonderfull Burgundy 
    url: /wonderfull-burgundy
  - label: Southern Burgundy 
    title:  Southern Burgundy 
    url: /southern-burgundy
  - label: about
    title: about
    url: /about
  - label: contact
    title: contact
    url: /contact
  - label: blog
    title: blog
    url: /blog


